# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNIntegration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNIntegration


  # Your 'node_modules' directory is probably in the root of your project,
    # but if not, adjust the `:path` accordingly

    # Explicitly include Yoga if you are using RN >= 0.42.0
    pod "Yoga", :path => "../js/node_modules/react-native/ReactCommon/yoga"

    pod 'React', :path => '../js/node_modules/react-native', :subspecs => [
      'Core',
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # needed for debugging
      # Add any other subspecs you want to use in your project
    ]


end
